### ISSUE TITLE
`edgeHash` is not safe to use for directed cyclic graphs

### ISSUE THREAD

**Issue by nrkramer** [ZigRazor/CXXGraph#324]
It seems `edgeHash` uses the XOR operator between two Node ids.

The issue with that is with a directed graph that has two `DirectedEdge`s with nodes that point towards each-other (i.e. a cycle), the hash will be the same, making it impossible to insert into a `CXXGraph::EdgeSet_T`.

See code below:
```
template <typename T>
struct edgeHash {
  size_t operator()(const shared<const Edge<T>>& edge) const {
    return (edge->getNodePair().first->getId()) ^ (edge->getNodePair().second->getId());
  }
};
```

### Concretely, this line is the problem:
`return (edge->getNodePair().first->getId()) ^ (edge->getNodePair().second->getId());`

Note that the `^` operator used is between two `size_t` calculated from the id (std::string) of the Node. The `^` operator is **symmetrical**, and will therefore return the same "hash" without regard for the actual direction of the edge.

`DirectedEdge` should use a hashing algorithm that takes the direction into account, perhaps by negating values or something.

Let me know if this makes sense.

**Comment by sbaldu** [comment]
I agree that in your example the hash index given by this function will be the same, so there is a conflict in the table, but the equality operator should be able to distinguish between the two edges.
In the `PointerHash.hpp` file where I defined the hash function, I also added an overload of the equality operator for shared pointers of edges:
```
template <typename T>
bool operator==(shared<const Edge<T>> p1, shared<const Edge<T>> p2) {
  return p1->getNodePair().first->getUserId() ==
             p2->getNodePair().first->getUserId() &&
         p2->getNodePair().second->getUserId() ==
             p2->getNodePair().second->getUserId();
}
```
In this way, even if two edges are given the same hash index, they won't be seen as the same, and will both be added to the set, because if they create a cycle the order of the nodes in the nodepair will be swapped.

Does it make sense or am I missing something?

**Comment by ZigRazor** [comment]
I think this can be verified with a simple testcase. Anyone can elaborate this testcase with failure result?

**Comment by sbaldu** [comment]
@ZigRazor I'll do it

**Comment by nrkramer** [comment]
> but the equality operator should be able to distinguish between the two edges.

I think I missed this. This does alleviate my concern, thanks! I'm still seeing some odd behavior where unique DirectedEdge's are not being added to the container, so I'll continue to investigate.

I'll open a PR shortly with a test to demonstrate my issue (realistically, I should have started with that).
