### ISSUE TITLE
Add Tests to Djikstra Algorithm

### ISSUE THREAD

**Issue by ZigRazor** [ZigRazor/CXXGraph#57]
There is the necessity to write more test on Djikstra Algorithm.
Specialy on limit case.
Any contribution is appreciated.

**Comment by AlfredCP** [comment]
@ZigRazor , I am looking at this algorithm to create tests and I have a question about how Graph handles the input.
What would happen if I have 2 edges with the same ID? Graph would accept it, right?

If there is a collision with Edges ID... I am wondering how we are using those IDs.
Since you have a wider view of the project, any idea about the impact this can have over all the other algorithms?

**Comment by ZigRazor** [comment]
> @ZigRazor , I am looking at this algorithm to create tests and I have a question about how Graph handles the input. What would happen if I have 2 edges with the same ID? Graph would accept it, right?
> 
> If there is a collision with Edges ID... I am wondering how we are using those IDs. Since you have a wider view of the project, any idea about the impact this can have over all the other algorithms?

The collision actually are not managed, but we can create a function to check graph integrity to check that all `edgeId `are different and add this check at the start of all algorithms, or at the insertion of an edge ( maybe better this second solution).
